version: 1
services:
  - type: web
    name: certidoes-api
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "uvicorn app:app --host 0.0.0.0 --port 8000"
    envVars:
      - key: HEADLESS
        value: "1"
      - key: TIMEOUT
        value: "30"
      - key: DRIVER_PATH
        value: "/usr/local/bin/chromedriver"
    autoDeploy: true
